### ISSUE TITLE
Props required for tournament customization

### ISSUE THREAD

**Issue by walkwel** [NUS-ALSET/games#16]
Run Tournament
Custom Code Tournament
Hide Tournament

buttons need to be passed as props to the Tournament component so that they can be controllable and customizable from the parent component.

Example:
RunTournament: True/False
CustomCodeTournament: True/False
HideTournament: True/False

**Comment by walkwel** [comment]
Hi @MKoth 
Kindly Check the game folder in achievement repo, I've changed the game codes as per the requirements of the game activity.

Check out these file for the reference:
1 /achievements/src/components/games/passenger-picker/view/App.js
2 /achievements/src/components/games/passenger-picker/view/updater.js

Main changes in these files are that game-data is coming from the props so that props can be pass from a game-activity to a game component.
 You need to implement similar changes in the Tournament to meet the requirement of Tournament activity.

Everything will be coming from the props so Keep in mind. A user doesn't have any option to change/select game parameter from Tournament Component. Tournament data come from a tournament activity and result will pass back to the parent component.

Thanks!

**Comment by walkwel** [comment]
These are sample of props sholud be used  by game/tournament component to communicate with Achievement Repo

```
player1Data={
    playMode : 'MANUAL' || 'CUSTOM_CODE',
    code : [ // if not preset, set default
    {
        pyCode : '', // for level 1 
        jsCode : ''
    },
    {
        pyCode : '', // for level 2
        jsCode : ''
    },
    {
        pyCode : '', // for level 3
        jsCode : ''
    }] // codes for multilevels
} 
player2Data={ // this is used in case of student vs student else set default
    playMode : 'MANUAL' || 'CUSTOM_CODE', // default 'CUSTOM_CODE'
    code : [
        {
            pyCode : '',
            jsCode : ''
        },
        {
            pyCode : '',
            jsCode : ''
        },
        {
            pyCode : '',
            jsCode : ''
        }] // 3 levels code
}
gameData={
    scoreToWinGame : 10,
    scoreToWinTournament : 20, // only need is case of tournament
    gameTime : 120, // in seconds
    numberOfUnits : 2, // or botQuantities,
    tournamentSocre: [
        [1.0, 1.0, 1.0], // [ score_of_player1_level1-VS-player2_level1, score_of_player1_level1-VS-player2_level2, score_of_player1_level1-VS-player2_level3 ]
        [0.0, 0.1, 0.0], //  [ score_of_player1_level2-VS-player2_level1 , ..., ...]
        [1.0, 0.0, 0.0] // ...
    ] // this is result of simulation which is saved into firebase Database
}
gameType = "GAME" || "TOURNAMENT" // in case of GAME disable simulation
onSimulationComplete //  pass simulation result / updated tournament score & this will update tournamentSocre in firebase database
onCommit/onComplete/onGameOver //  pass result of game (WIN/LOOSE/EQUAL) & updated code by user & level_Number and run simulation after game complete so that tournament score will update

```
![screenshot from 2018-10-04 05-20-07](https://user-images.githubusercontent.com/23698860/46445603-60a0b700-c795-11e8-9fed-6cd53f719ebe.png)

**Comment by MKoth** [comment]
Hi @walkwel 
![image](https://user-images.githubusercontent.com/10651614/46569364-9217af00-c95c-11e8-85a5-8b2c15bad1e2.png)

**Comment by walkwel** [comment]
Hi @MKoth ,
![screenshot](https://user-images.githubusercontent.com/23698860/46575535-62a48900-c9d4-11e8-9caf-2faaec086ff3.png)

**Comment by MKoth** [comment]
According to what is done and just, got confirmation from @scboesch, that student will submit only one bot controlling code that will compete with 1-3 or more levels, there is no such thing as level1_player1 vs. level1_player2, since level1 will never compete vs. level1 of other player. Currently in tournament table there is no possibility to compete level1 against level1, since it the same level function, that's why there is empty cell at cross point between this functions

![image](https://user-images.githubusercontent.com/10651614/46630585-4e37cc00-cb4d-11e8-8dd5-7641277fba73.png)

**Comment by MKoth** [comment]
![image](https://user-images.githubusercontent.com/10651614/46630839-1715ea80-cb4e-11e8-8f68-a45b08c9f075.png)

**Comment by MKoth** [comment]
![image](https://user-images.githubusercontent.com/10651614/46661553-1a4abe00-cbc2-11e8-8255-1667d4129f88.png)

**Comment by walkwel** [comment]
Yes, I also got that confirmation from @scboesch 
Let's keep it like this and let me re-analyze the code and update you.

**Comment by MKoth** [comment]
Hi @walkwel have you got a chance to re-anylize code, otherwise I can implement it the way I suggested?

**Comment by walkwel** [comment]
Hi @MKoth 
I've created a PR regarding these changes.
Please review the PR.
Or check on code [codesandbox](https://codesandbox.io/s/github/walkwel/games/tree/master/src/passengerPickup)
 
This code is working for Game activity & but checked for the tournament.
