### ISSUE TITLE
Click on head to head match - should be handled properly.

### ISSUE THREAD

**Issue by walkwel** [NUS-ALSET/games#17]
Users can click on the result of any head-to-head match to play a given bot as player 1 or player 2. 

Currently, this is achieved by href on A tag. There needs to be a method pass to the element from the parent component that will be responsible to re-render the game with selected controls.

Refer to this code
https://github.com/NUS-ALSET/games/blob/master/src/squadSinglePlayerGame/src/simulation/table-result.js#L94

https://github.com/NUS-ALSET/games/blob/master/src/squadSinglePlayerGame/src/simulation/table-result.js#L100

**Comment by MKoth** [comment]
Updated version on games repo is having this functionality implemented
